---
title: "Setting up project environment"
---

> [!IMPORTANT]
> See the software install instructions: [Software Install README](software_install_README.md) before setting up your environment.

- [Steps](#steps)
- [Clone code repo](#clone-code-repo)
- [Download input files](#download-input-files)
- [Restore Environments (packages and libraries)](#restore-environments-packages-and-libraries)
  - [Python Virtual Environment (`venv`)](#python-virtual-environment-venv)
  - [R Reproducible Environment (`{renv}`)](#r-reproducible-environment-renv)
- [Primary Development Environment (Session Info)](#primary-development-environment-session-info)
  - [Python](#python)
  - [R](#r)

# Steps
1. Install software
2. Clone project code repo
3. Dowload input data from SharePoint
4. Activate and restore python and R environments/libraries

# Clone code repo
- [Clone from GitHub instructions](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository)
- [Set up Git](https://docs.github.com/en/get-started/git-basics/set-up-git)

# Download input files
The following files must exist in the [ky_data](../../ky_data/) directory. Download them from the SharePoint folder: [/KYWSS-Home/ky-data/](https://kymsoffice.sharepoint.com/:f:/r/teams/KYWastewaterSurveillanceCHFSDPH-MSTeams/Shared%20Documents/KYWSS-Home/ky-data?csf=1&web=1&e=guHuhC)
1. KYWSS_regions.csv
2. KY_wastewater_sites.xlsx
3. KySewersheds.geojson
4. Ky_County_Polygons_WM_-3915653526132611478.geojson
5. Ky_County_Polygons_WM_344776173949753501.csv
6. DLS+UK+UL_COMBINED_Data.csv (from SharePoint folder: [\KYWSS-Home\Cumulative_1CDP_Data\Merged_Data\DLS+UK+UL_COMBINED_Data.csv](https://kymsoffice.sharepoint.com/:f:/r/teams/KYWastewaterSurveillanceCHFSDPH-MSTeams/Shared%20Documents/KYWSS-Home/Cumulative_1CDP_Data/Merged_Data?csf=1&web=1&e=MaTZE1))
7. Ky_Major_Roads.geojson (from SharePoint folder: "\KYWSS-Home\ky-data\infrastructure\")
8. PLACES__County_Data__GIS_Friendly_Format___2024_release.csv *from https://catalog.data.gov/dataset/places-county-data-gis-friendly-format-2020-release-9c9e8
9. WW_Popoulation.csv *from KYWSS-Home/ky_data/ ** this dataset was generated by KIA and emailed to Daniel

# Restore Environments (packages and libraries)
## Python Virtual Environment (`venv`)
Please see the [requirement.txt file](../../requirements.txt) for a list of python libraries.

Follow the instructions [here](https://quarto.org/docs/projects/virtual-environments.html) to create, activate, and restore libraries using `requirement.txt`.

## R Reproducible Environment (`{renv}`)
Please see the [renv.lock file](../../renv.lock) for a list of R packages.

Instructions:
1. Clone the project from GitHub into a local folder, open folder in IDE of choice (be sure that the project directory is recognized/set correctly)
2. If {renv} does not bootstrap/install itself, install manually using `install.packages("renv")`
3. Restore R environment by running the following line of code in the R Console: `renv::init()` -> Choose option 1 to restore project

{renv} documentation: [Collaborating with renv](https://pkgs.rstudio.com/renv/articles/collaborating.html)

# Primary Development Environment (Session Info)
## Python
- Python Version: 3.11.9
- Implementation: CPython
- System: Windows
- Release: 10
- Machine: AMD64
- Processor: Intel64 Family 6 Model 186 Stepping 2, GenuineIntel

## R
- R version 4.4.1 (2024-06-14 ucrt)
- Platform: x86_64-w64-mingw32/x64
- Running under: Windows 11 x64 (build 22631)
